apiVersion: apps/v1
kind: Deployment
metadata:
  name: atonixforge-deployments
  namespace: atonixcorpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atonixforge
  template:
    metadata:
      labels:
        app: atonixforge
    spec:
      containers:
      - name: atonixforge
        image: ofidohubvm/atonixforge:latest
        ports:
        - containerPort: 3002
      imagePullSecrets:
      - name: ofidohubvm-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: atonixforge
  namespace: atonixcorpvm
spec:
  selector:
    app: atonixforge
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer